<h1>Mangez des pâtes</h1>

<article>
    <figure class="fig-left">
        <img src="https://cdn.stocksnap.io/img-thumbs/960w/pasta-flour_I4MIIMHZ5M.jpg" alt="des_pates">
        <figcaption>
            <h2>Interview d'un éleveur de pâtes</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum laboriosam, omnis non maiores ipsum corrupti laborum, saepe, dignissimos veritatis harum illum nulla veniam voluptas velit. Voluptate quasi nihil voluptatem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum laboriosam, omnis non maiores ipsum corrupti laborum, saepe, dignissimos veritatis harum illum nulla veniam voluptas velit. Voluptate quasi nihil voluptatem.</p>
            <a href="#">Suite de l'interview</a>
        </figcaption>
    </figure>

    <figure class="fig-right">
        <img src="https://cdn.stocksnap.io/img-thumbs/960w/food-pasta_K5SKTOQN0U.jpg" alt="encore_des_pates">
        <figcaption>
            <h2>Les pâtes c'est la vie</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum laboriosam, omnis non maiores ipsum corrupti laborum, saepe, dignissimos veritatis harum illum nulla veniam voluptas velit. Voluptate quasi nihil voluptatem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum laboriosam, omnis non maiores ipsum corrupti laborum, saepe, dignissimos veritatis harum illum nulla veniam voluptas velit. Voluptate quasi nihil voluptatem.</p>
            <a href="#">Suite de l'interview</a>
        </figcaption>
    </figure>
</article>