<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projet 3W Academy - Laure Dominguez</title>
    <link rel="stylesheet" href="./assets/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">	<!--Font Awesome 6-->
    <script src="https://kit.fontawesome.com/267127ee95.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-toggler bg-light">
            <ul class="nav">
                <li><a href="index.php?page=home">Accueil</a></li>
                <li><a href="index.php?page=shopadmin">Boutique-admin</a></li>
                <li><a href="index.php?page=shopuser">Boutique-user</a></li>
                <li><a href="index.php?page=contact">Contact</a></li>
            </ul>
            <ul class="nav dropdown-center">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Mon Compte</a>
                    <ul class="dropdown-menu">
                        <li><a href="?page=register" class="dropdown-item">Création</a></li>
                        <li><a href="?page=login" class="dropdown-item">Connexion</a></li>
                        <li><a href="#" class="dropdown-item">Profil</a></li>
                        <li class="divider"><hr class="dropdown-divider"></li>
                        <li><a href="#" class="dropdown-item">Déconnexion</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
    <main class="container">
        <?=$content?>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="./assets/custom.js"></script>
</body>
</html>