<h1>Nouvel utilisateur</h1>

<form method="POST" action="?page=login" class="formulaire">
    <div>
        <label for="email" class="form-label">Email</label>
        <input type="email" name="email" id="email" class="form-control" required>
        <br>
        <label for="password" class="form-label">Mot de passe</label>
        <input type="password" name="password" id="password" class="form-control" required>
        
        <!-- <br>
        <label for="birthday" class="form-label">Date de naissance</label>
        <input type="date" name="birthday" id="birthday" class="form-control" required>
        <br>
        <label for="firstname" class="form-label">Prénom</label>
        <input type="text" name="firstname" id="firstname" class="form-control" required>
        <br>
        <label for="lastname" class="form-label">Nom</label>
        <input type="text" name="lastname" id="lastname" class="form-control" required>
        <br>
        <label for="address" class="form-label">Adresse</label>
        <input type="text" name="address" id="address" class="form-control">*
        <br>
        <label for="city" class="form-label">Ville</label>
        <input type="text" name="city" id="city" class="form-control" required>
        <br>
        <label for="citycode" class="form-label">Code postal</label>
        <input type="number" name="citycode" id="citycode" class="form-control" required>
        <br>
        <label for="phone" class="form-label">Tléléphone</label>
        <input type="tel" name="phone" id="phone" class="form-control" required>
        <br>
        <fieldset>
            <legend>Genre</legend>
            <label for="male" class="form-label">Homme</label>
            <input type="radio" name="male" value="male">
            <br>
            <label for="female" class="form-label">Femme</label>
            <input type="radio" name="female" value="female">
            <br>
            <label for="none" class="form-label">Autre</label>
            <input type="radio" name="none" value="none">
        </fieldset> -->
    <button type="submit">Valider</button>
</form>